source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails', '4.1.8'
gem 'protected_attributes'
gem 'rails-observers'
gem 'bourbon'
gem 'dalli'
gem 'thin'
#gem 'newrelic_rpm'
gem 'font_assets'
gem 'exception_notification'
gem 'active_model_serializers'
gem 'sass-rails', '4.0.5'
gem 'uglifier', '~> 2.5.3'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-ui-rails', '~> 5.0.3'
# gem 'font-awesome-rails', "= 3.2.1.3"
gem 'font-awesome-rails', '~> 4.2'
gem 'sqlite3'
gem 'jquery-rails', '~> 3.1.2'
